### PR TITLE
#408-add support for authentication in soda-spark

### PR DESCRIPTION
**Pull request by abhishek-khare**
This PR contains the fix for #408.

- Added a parameter `authentication` for the `warehouse.yml`.

Eg value - `authentication: LDAP`

### CODE REVIEW

**Comment by vijaykiran** [comment]
Thank you @abhishek-khare !

**Comment by abhishek-khare** [comment]
@vijaykiran is it the same reason for build failures ? 

https://github.com/sodadata/soda-sql/pull/366#issuecomment-868556100

**Comment by vijaykiran** [comment]
yes, it is because the builds are run in your fork's context, I'll add this in a branch and run the tests before merging, no worries.

**Comment by abhishek-khare** [comment]
> yes, it is because the builds are run in your fork's context, I'll add this in a branch and run the tests before merging, no worries.

ok cool 👍🏾

**Comment by vijaykiran** [comment]
@all-contributors please add @abhishek-khare for code

**Pull request merged**
