### PR TITLE
Spelling fix

### PR DESCRIPTION
**Pull request by fbertsch**

### CODE REVIEW

**Comment by vijaykiran** [comment]
@janet-can  can you please check and merge?

**Comment by vijaykiran** [comment]
Hi @fbertsch  Thanks so much for the PR, can you please sign the CLA, so we can merge your changes?

**Comment by fbertsch** [comment]
Sorry, I'm not an attorney and can't parse that CLA.

**Comment by tombaeyens** [comment]
@fbertsch, no worries.  Still big thanks for pointing it out :)  We'll apply the fix ourselves.

**Pull request closed without merging**
